### PR TITLE
Fix remainder of spec urls.

### PR DESCRIPTION
**Pull request by luciansmith**

### CODE REVIEW

**Comment by luciansmith** [comment]
https://identifiers.org/combine.specifications:sbml.level-2.version-3.release-1 doesn't actually work; there's apparently only l2v3r2 out there?  @matthiaskoenig do you know if l2v3r1 is somewhere we can find?

**Comment by matthiaskoenig** [comment]
@luciansmith I added the entry https://identifiers.org/combine.specifications:sbml.level-2.version-3.release-1, but would need
- specification PDF or the L2V3R1
- release date (should be on the PDF)
- authors (should be on the PDF)

**Comment by luciansmith** [comment]
[SBML_Level_2_Version_3.pdf](https://github.com/sbmlteam/sbml-org-website/files/10746551/SBML_Level_2_Version_3.pdf)

**Comment by luciansmith** [comment]
OK!  Actual spec:

https://github.com/sbmlteam/sbml-specifications/blob/81bc5b054da7fd62fe32705211f83e6464f6cae4/sbml-level-2/version-3/spec/sbml-level-2-version-3.pdf

**Comment by luciansmith** [comment]
Release date: June 12, 2007
Authors:  Michael Hucka, Andrew M. Finney, Stefan Hoops, Sarah M. Keating, Nicolas Le Nov`ere

**Comment by matthiaskoenig** [comment]
All information added on the COMBINE specification. I think this can be merged here.

**Pull request merged**
